import random
import datetime

start_date = datetime.date(2021, 12, 1)
end_date = datetime.date(2022, 1, 1)

time_between_dates = end_date - start_date
days_between_dates = time_between_dates.days

feedback = [1, 2, 3]
type = ['single', 'coached', 'double']

sample_data = {
            "data": [
                {
                    "cardId": 5561,
                    "accountId": 5561,
                    "accountName": "116634_م/ تبارك السابع_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "السابع",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 732,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5561,
                            "name": "116634_م/ تبارك السابع_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5563,
                    "accountId": 5563,
                    "accountName": "119377_مستشفى كيدز_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينة نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 734,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5563,
                            "name": "119377_مستشفى كيدز_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5564,
                    "accountId": 5564,
                    "accountName": "119379_مستشفى الهدى التخصصى_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينه نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 735,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5564,
                            "name": "119379_مستشفى الهدى التخصصى_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5565,
                    "accountId": 5565,
                    "accountName": "22725_مستشفي التامين الصحي_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مستشفي مدينه نصر - شارع يوسف عباس",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 736,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5565,
                            "name": "22725_مستشفي التامين الصحي_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5567,
                    "accountId": 5567,
                    "accountName": "29658_شركه اي ان تي كلينك انف و اذن_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينه نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 738,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5567,
                            "name": "29658_شركه اي ان تي كلينك انف و اذن_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5579,
                    "accountId": 5579,
                    "accountName": "65791_مستشفى دار الحكمة_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينة نصر- القاهره",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 750,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5579,
                            "name": "65791_مستشفى دار الحكمة_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5585,
                    "accountId": 5585,
                    "accountName": "109189_دار الفؤاد مستشفى النصر_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "ﻁﺭﻴﻕ ﺍﻟﻨﺼﺭﻤﻊ ﺵ ﻴﻭﺴﻑ ﻋﺒﺎﺱ ﺍﺭﺽ ﺍﻟﻐﺎﺒﺓ",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 756,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5585,
                            "name": "109189_دار الفؤاد مستشفى النصر_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5597,
                    "accountId": 5597,
                    "accountName": "66056_مستشفى مركز جامع رابعة العدوية_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "ميدان رابعة العدوية -مدينة نصر-القاهرة",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 768,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5597,
                            "name": "66056_مستشفى مركز جامع رابعة العدوية_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5601,
                    "accountId": 5601,
                    "accountName": "مستشفي الأزهر التخصصى_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينة نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 772,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5601,
                            "name": "مستشفي الأزهر التخصصى_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 5602,
                    "accountId": 5602,
                    "accountName": "118898_مستشفى شفا التخصصى_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينه نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 773,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 5602,
                            "name": "118898_مستشفى شفا التخصصى_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7871,
                    "accountId": 7871,
                    "accountName": "عيادات المقاولون العرب_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينه نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7350,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7871,
                            "name": "عيادات المقاولون العرب_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7872,
                    "accountId": 7872,
                    "accountName": "مستشفي جراحات اليوم الواحد_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "الحي السادس",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7351,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7872,
                            "name": "مستشفي جراحات اليوم الواحد_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7873,
                    "accountId": 7873,
                    "accountName": "مستشفي صحة العقاد_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "عباس العقاد",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7352,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7873,
                            "name": "مستشفي صحة العقاد_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7874,
                    "accountId": 7874,
                    "accountName": "مستشفي التوفيقية_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "عباس العقاد",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7353,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7874,
                            "name": "مستشفي التوفيقية_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7875,
                    "accountId": 7875,
                    "accountName": "مستشفي الماسه_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينة نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7354,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7875,
                            "name": "مستشفي الماسه_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7876,
                    "accountId": 7876,
                    "accountName": "مستشفي النهار_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينة نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7355,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7876,
                            "name": "مستشفي النهار_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7877,
                    "accountId": 7877,
                    "accountName": "مستشفي اورام مدينة نصر_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "الطيران",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7356,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7877,
                            "name": "مستشفي اورام مدينة نصر_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7992,
                    "accountId": 7992,
                    "accountName": "التامين الصحي مدينه نصر_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "شارع الطيران",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7469,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7992,
                            "name": "التامين الصحي مدينه نصر_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7993,
                    "accountId": 7993,
                    "accountName": "مستشفي الاورام مدينه نصر_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "شارع الطيران بجانب التامين الصحي",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7470,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7993,
                            "name": "مستشفي الاورام مدينه نصر_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7995,
                    "accountId": 7995,
                    "accountName": "مستشفي رابعه العدويه_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "ميدان رابعه العدويه",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7472,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7995,
                            "name": "مستشفي رابعه العدويه_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7996,
                    "accountId": 7996,
                    "accountName": "مستشفي الشيخ زايد ال نهيان_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "امتداد طريق النصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7473,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7996,
                            "name": "مستشفي الشيخ زايد ال نهيان_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7997,
                    "accountId": 7997,
                    "accountName": "مستشفي الشرطه مدينه نصر_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": "الحي السابع مدينه نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7474,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7997,
                            "name": "مستشفي الشرطه مدينه نصر_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 7999,
                    "accountId": 7999,
                    "accountName": "تيسير الحي السابع_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "امتداد الطيران الحى السابع",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 7476,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 7999,
                            "name": "تيسير الحي السابع_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13114,
                    "accountId": 13114,
                    "accountName": "عبد القادر فهمي _AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "مدينه نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12363,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13114,
                            "name": "عبد القادر فهمي _AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13118,
                    "accountId": 13118,
                    "accountName": "التامين الصحي مدينه نصر_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "شارع الطيران",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12367,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13118,
                            "name": "التامين الصحي مدينه نصر_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13121,
                    "accountId": 13121,
                    "accountName": "مستشفي الشيخ زايد ال نهيان_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "امتداد طريق النصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12370,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13121,
                            "name": "مستشفي الشيخ زايد ال نهيان_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13122,
                    "accountId": 13122,
                    "accountName": "مستشفي الشرطه مدينه نصر_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": "الحي السابع مدينه نصر",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12371,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13122,
                            "name": "مستشفي الشرطه مدينه نصر_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13124,
                    "accountId": 13124,
                    "accountName": "المقاولون_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": "امتداد رمسيس امام م.صدر العباسيه",
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12373,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13124,
                            "name": "المقاولون_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13360,
                    "accountId": 13360,
                    "accountName": "مستشفى جامعه الازهر_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12609,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13360,
                            "name": "مستشفى جامعه الازهر_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13362,
                    "accountId": 13362,
                    "accountName": "مستشفى رابعه_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12611,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13362,
                            "name": "مستشفى رابعه_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13364,
                    "accountId": 13364,
                    "accountName": "مستشفى الحكمه_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12613,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13364,
                            "name": "مستشفى الحكمه_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13365,
                    "accountId": 13365,
                    "accountName": "مستشفى الجودى_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 1,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12614,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13365,
                            "name": "مستشفى الجودى_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13366,
                    "accountId": 13366,
                    "accountName": "حميات العباسيه_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12615,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13366,
                            "name": "حميات العباسيه_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13368,
                    "accountId": 13368,
                    "accountName": "مستشفى الشرطه الحى السابع_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 1,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12617,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13368,
                            "name": "مستشفى الشرطه الحى السابع_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13369,
                    "accountId": 13369,
                    "accountName": "مستشفى جراحات اليوم الواحد_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12618,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13369,
                            "name": "مستشفى جراحات اليوم الواحد_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13372,
                    "accountId": 13372,
                    "accountName": "مستشفى السفارات_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12621,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13372,
                            "name": "مستشفى السفارات_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13373,
                    "accountId": 13373,
                    "accountName": "مستشفى كيور_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12622,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13373,
                            "name": "مستشفى كيور_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 13374,
                    "accountId": 13374,
                    "accountName": "مستشفى العقاد_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 3,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 12623,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 13374,
                            "name": "مستشفى العقاد_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 14731,
                    "accountId": 14731,
                    "accountName": "مسنشفى المقاولين_Nasr City 2_AM",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 2,
                    "accountClass": "B",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 13980,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 14731,
                            "name": "مسنشفى المقاولين_Nasr City 2_AM"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                },
                {
                    "cardId": 17751,
                    "accountId": 17751,
                    "accountName": "مستشفى التامين الصحى مدينه نصر_AM_Nasr City 2",
                    "accountCategory": 1,
                    "accountTypeId": 1,
                    "accountType": "AM",
                    "professionalId": None,
                    "professionalName": None,
                    "accountClassId": 1,
                    "accountClass": "A",
                    "address": None,
                    "brickId": 402,
                    "brickName": "Nasr City 2",
                    "specialityId": 17,
                    "specialityName": "AM",
                    "defaultVisits": 0,
                    "selectedVisits": 2,
                    "cardColor": None,
                    "assignType": 1,
                    "clinicId": 16886,
                    "clinicSpecialityId": 0,
                    "visitGap": 0,
                    "visitId": None,
                    "callId": None,
                    "visitDate": None,
                    "sequence": None,
                    "professionals": [
                        {
                            "id": 17636,
                            "name": "مستشفى التامين الصحى مدينه نصر_AM_Nasr City 2"
                        }
                    ],
                    "periodDate": 0,
                    "periodExecutionDateFrom": 0,
                    "periodExecutionDateTo": 0,
                    "createdBy": None,
                    "currentUserId": None,
                    "currentStatusId": 0,
                    "currentStepId": 0,
                    "userId": 0,
                    "planId": 0,
                    "callsIds": None,
                    "repName": None,
                    "planDates": None,
                    "currentPeriod": False
                }
            ]
        }

sample_events = {"events": list()}

for i in range(108):

    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)

    event_day = datetime.datetime.strftime(random_date, "%Y-%m-%d")
    event_status = "upcoming" if datetime.datetime.now().date() < random_date else random.choice(["in-progress", "done", "missed"])

    client = random.choice(sample_data['data'])
    sample_events["events"].append( {    
                                        "day": event_day,
                                        "client": client,
                                        "status": event_status,
                                        "details": {
                                            "type": random.choice(type),
                                            "feedback": 3 if event_status == "missed" else random.choice(feedback),
                                            "feedbackNotes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                                            "products": [
                                                {
                                                    "name": 'product ' + str(i),
                                                    "feedback": random.choice(feedback),
                                                    "feedbackNotes": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                                                } for i in range(random.randint(0,4))
                                            ]
                                        },
                                    } )