# Generated by Django 3.2.5 on 2021-12-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_name', models.CharField(max_length=255, unique=True)),
                ('ar_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_name', models.CharField(max_length=255)),
                ('ar_name', models.CharField(max_length=255)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shared.governorate')),
            ],
        ),
    ]
