# Generated by Django 3.2.5 on 2021-12-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_clientspecialty_specialty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['en_name', 'ar_name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='clientspecialty',
            options={'verbose_name': 'Client Specialty', 'verbose_name_plural': 'Client Specialties'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'ordering': ['en_name', 'ar_name']},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['en_name', 'ar_name'], 'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
    ]
