# Generated by Django 3.2.12 on 2022-02-24 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('brochure', models.FileField(blank=True, upload_to='uploads/inventory/products/', validators=[inventory.models.Product.validate_file_extension])),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.line')),
            ],
        ),
    ]
