# Generated by Django 3.2.5 on 2021-12-26 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0016_auto_20211226_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bd60305d-34c6-470d-bf77-149bb08e4387'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bbe0aa02-a2ed-4fb3-8cee-1c0e3a847059'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.line')),
            ],
        ),
    ]
