# Generated by Django 3.2.5 on 2021-12-26 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ec2b510-76b5-4122-8c71-d5d0cbc8a15c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e10425a-c490-4dd0-ae19-75f72edde09c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
