# Generated by Django 3.2.5 on 2021-12-27 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211226_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e882477-e237-4ea4-acf3-4fc97120cc4e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49eaf97b-4a86-4e6f-81cb-11df40419aa4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
