# Generated by Django 3.2.5 on 2021-12-27 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211227_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3648d1b8-05e8-4259-8e27-09df3dbbd8fe'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('802b7180-a629-44a7-b84e-f74dfcc691aa'), primary_key=True, serialize=False, unique=True),
        ),
    ]
