# Generated by Django 3.2.5 on 2021-12-27 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211227_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, upload_to='uploads/inventory/products/'),
        ),
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea2cc580-4ee4-4423-8db4-15450eb3351b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3651de7f-f352-4bd9-87ae-af3b8fc4eb27'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.line'),
        ),
    ]
