# Generated by Django 3.2.5 on 2021-12-27 22:11

from django.db import migrations, models
import inventory.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211227_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fc0a9a9-bbac-4420-aac4-6c2acd98087e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, upload_to='uploads/inventory/products/', validators=[inventory.models.Product.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35706db1-9a04-4a20-ad0c-5bcfdee5989c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
