# Generated by Django 3.2.5 on 2021-12-27 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211227_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bb9d96c-92cc-45da-ac3b-566d11d4e092'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11d57d80-7710-464e-be93-1fdf5b409b2f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
