# Generated by Django 3.2.5 on 2021-12-27 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211227_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea878598-f80e-4012-a5e5-e5d859fa3bc7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f9557d1-f725-4986-8b71-58f672aabc46'), primary_key=True, serialize=False, unique=True),
        ),
    ]
