# Generated by Django 3.2.5 on 2021-12-19 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('479063ef-1d1a-41fd-9107-b850a2de4f83'), primary_key=True, serialize=False, unique=True),
        ),
    ]
