# Generated by Django 3.2.5 on 2021-12-20 18:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211220_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84045bf1-d352-4511-9bc0-c2104dac8b70'), primary_key=True, serialize=False, unique=True),
        ),
    ]
