# Generated by Django 3.2.5 on 2021-12-20 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211220_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('662be195-b11f-4e55-935d-cd0f68bfbdee'), primary_key=True, serialize=False, unique=True),
        ),
    ]
