# Generated by Django 3.2.5 on 2021-12-20 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4334968-b99c-420b-8a84-909c372d7685'), primary_key=True, serialize=False, unique=True),
        ),
    ]
