# Generated by Django 3.2.5 on 2021-12-20 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d31684ca-f8e6-43b3-9ee2-a9c0605e9e85'), primary_key=True, serialize=False, unique=True),
        ),
    ]
