# Generated by Django 3.2.5 on 2021-12-20 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68d5b516-f438-4b55-b6da-25c151458b4a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
