# Generated by Django 3.2.5 on 2021-12-20 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2e0edd8-df2a-4b26-b73a-c60f98ef4233'), primary_key=True, serialize=False, unique=True),
        ),
    ]
