# Generated by Django 3.2.5 on 2021-12-20 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('492de966-4db9-4c7f-bb01-f5e7029cf460'), primary_key=True, serialize=False, unique=True),
        ),
    ]
