# Generated by Django 3.2.5 on 2021-12-20 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0eaf9bc5-875d-4efb-bba5-1c6b3f103f2d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
