# Generated by Django 3.2.5 on 2021-12-20 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9bd094f0-999c-4b01-ba29-049e866ecf1c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
