# Generated by Django 3.2.5 on 2021-12-20 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a905692f-1c24-47c0-8533-5d2453687fa0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
