# Generated by Django 3.2.5 on 2021-12-20 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4a38fed-a720-4908-a57d-85f71530eb1d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
