# Generated by Django 3.2.5 on 2021-12-20 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bee15dde-db3d-41e0-9df6-e7d5a1122014'), primary_key=True, serialize=False, unique=True),
        ),
    ]
