# Generated by Django 3.2.5 on 2021-12-20 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75a3338b-8c87-4583-a7b9-94a0213e3280'), primary_key=True, serialize=False, unique=True),
        ),
    ]
