# Generated by Django 3.2.5 on 2021-12-21 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65864c2a-2a02-4bd9-991f-a42e5ca9821c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
