# Generated by Django 3.2.5 on 2021-12-23 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6eb5370-4723-4972-aca7-1c81cacaaa0b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
