# Generated by Django 3.2.5 on 2021-12-26 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4a86025-ac3a-4c4a-9763-95b7f4fa1c56'), primary_key=True, serialize=False, unique=True),
        ),
    ]
