# Generated by Django 3.2.5 on 2021-12-26 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0976b3a9-702d-4131-be06-9f3a90db0f63'), primary_key=True, serialize=False, unique=True),
        ),
    ]
