# Generated by Django 3.2.5 on 2021-12-26 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cd58c6f-db18-494f-89c2-c03bb8e74dd6'), primary_key=True, serialize=False, unique=True),
        ),
    ]
