# Generated by Django 3.2.5 on 2021-12-26 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9be2d1ca-5010-4e84-8c75-da788c8bbf92'), primary_key=True, serialize=False, unique=True),
        ),
    ]
