# Generated by Django 3.2.5 on 2021-12-27 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a85aa24a-999b-46c7-b5d5-fe7a5d9f9388'), primary_key=True, serialize=False, unique=True),
        ),
    ]
