# Generated by Django 3.2.5 on 2021-12-27 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3798b7df-fd5e-4736-a7b6-a4e65231f665'), primary_key=True, serialize=False, unique=True),
        ),
    ]
