# Generated by Django 3.2.5 on 2021-12-27 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40f3e1d1-a856-421c-85a7-a667ac6bbd47'), primary_key=True, serialize=False, unique=True),
        ),
    ]
