# Generated by Django 3.2.5 on 2021-12-27 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b903bb22-e1e4-4caf-8632-513e3443ad12'), primary_key=True, serialize=False, unique=True),
        ),
    ]
