# Generated by Django 3.2.12 on 2022-02-24 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Business name')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Company preferred domain')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('size', models.IntegerField(verbose_name='Company size')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['name', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDistrict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictBrick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('type', models.CharField(choices=[('UNIT_HEAD', 'UNIT_HEAD'), ('DISTRICT_MANAGER', 'DISTRICT_MANAGER'), ('MEDICAL_REP', 'MEDICAL_REP')], max_length=255)),
                ('leaves_balance', models.IntegerField(default=21)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='business.business')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Unit name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='UnitHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.employee')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.unit')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='business.employee')),
                ('sales_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='business.salesteam')),
            ],
        ),
        migrations.AddField(
            model_name='salesteam',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='business.unit'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('LEAVE', 'LEAVE'), ('COACHED_VISIT', 'COACHED_VISIT'), ('PLAN', 'PLAN')], default='LEAVE', max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SEEN', 'SEEN'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='UPCOMING', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='business.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('SICK', 'SICK'), ('CASUAL', 'CASUAL'), ('VACATION', 'VACATION'), ('NATIONAL_HOLIDAY', 'NATIONAL_HOLIDAY')], default='CASUAL', max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='business.request')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictEmplyoee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessdistrict')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='business.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictEmployeeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='business.districtemplyoee')),
            ],
        ),
    ]
