# Generated by Django 3.2.12 on 2022-02-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('business', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtemployeeline',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='inventory.line'),
        ),
        migrations.AddField(
            model_name='districtbrick',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricks', to='business.businessdistrict'),
        ),
        migrations.AddField(
            model_name='businessdistrict',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='business.business'),
        ),
        migrations.AddField(
            model_name='businessdistrict',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.city'),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='business.business'),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='shared.client'),
        ),
    ]
