# Generated by Django 3.2.5 on 2021-12-20 21:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06ee0bf2-df34-4d8b-a84a-130c44400c21'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55bc6abd-ffca-4223-ba4b-9167df59c1c0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a07254d-9fd1-4884-87eb-a2687af622a3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e846d551-1227-4e05-b25f-a6d4db013189'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bb02458-70b8-4b62-bf65-718c68fd9f15'), primary_key=True, serialize=False, unique=True),
        ),
    ]
