# Generated by Django 3.2.5 on 2022-03-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtbrick',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bricks', to='business.businessdistrict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='districtemployeeline',
            name='line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='inventory.line'),
            preserve_default=False,
        ),
    ]
