# Generated by Django 3.2.5 on 2021-12-20 21:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20211220_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7c9d873-b598-466a-98a4-a69eff420e21'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.city'),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5029ea6-b892-4fac-aa05-34783573eccd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('755dba8c-7700-492a-9ac7-d3c88cb0f863'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessunithead',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='businessunithead',
            name='unit_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.businessunit'),
        ),
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.governorate'),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.businessdistrict'),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93908465-3ea4-4c7d-9bcb-7cd534594024'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.businessunit'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('733ff14f-38d9-4d4e-888b-eeceff45158e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='sales_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.salesteam'),
        ),
    ]
