# Generated by Django 3.2.5 on 2021-12-20 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20211220_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8dd39989-a03b-42d2-8974-edb212116ae5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.city'),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('50d89934-2323-498c-8698-09f0b632a9bc'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c6b060d-d112-478a-b808-9233211c03fe'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessunithead',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='businessunithead',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessunit'),
        ),
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.governorate'),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessdistrict'),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f867a527-eb79-4b06-bfb0-7d1bf0bb0191'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessunit'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c98b8f50-8166-4b02-9916-d1daf454d689'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='sales_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.salesteam'),
        ),
    ]
