# Generated by Django 3.2.5 on 2021-12-20 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20211220_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39f14ef1-cc03-46be-a864-8f311d211cc0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('817a1039-a8fd-42eb-929c-40638d35f699'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6957343-a6ab-4516-99e3-b68fa888597a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63623895-0654-4c66-9946-17cf567059ba'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ee9a8069-703a-48e3-8ad6-62fdf5cb3f6f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
