# Generated by Django 3.2.5 on 2021-12-20 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20211220_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8cd7c157-54a2-497f-a49d-0f6b0a7c285f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b51b4b30-b8d6-4b2c-9300-4a6fc9bb2b96'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce0c81e2-a6fe-4623-80bd-fb673b29b08e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84fa7165-0c6e-4447-bdec-f4aa8f6c2624'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a59121d1-9b20-4ded-8266-a8797e1a6e21'), primary_key=True, serialize=False, unique=True),
        ),
    ]
