# Generated by Django 3.2.5 on 2021-12-20 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20211220_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7acf3e66-2268-4f1f-b0e8-a23271cbe0d5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1580c3a-1758-4866-aeec-169ca7c24a84'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='business.governorate'),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='business.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='business.business'),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bcd9a8c-2b22-45d7-be8b-8507104691e8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='business.unit'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='business.employee'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21be56f1-cd91-46c0-bdf1-451a402bb1e7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='sales_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='business.salesteam'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='business.business'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa111709-48a0-45fd-9ca3-b0b83632e53c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
