# Generated by Django 3.2.5 on 2021-12-26 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20211223_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('135e0f54-5e5f-4b6b-8e3d-e59c005ee49b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55dd47dc-722f-41d5-9c98-90ba7d5afad6'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34dfafb6-fc85-4406-a666-e8872a193a4c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9531ee89-a5ed-4b2a-993a-3e3420da86a8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2d90a1f-8cce-4a81-be84-d2b418dbb2a2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
