# Generated by Django 3.2.5 on 2021-12-26 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20211226_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b3f3738-ad87-4a99-8169-767d1f2f14f9'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abaca593-2236-4441-8e2f-d210f989480f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7002e93-e189-4d91-ad04-ed94b6b48782'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5e2536f-a63b-4794-915b-70a35a880b4a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1892b903-d5f5-4433-a217-83f538b3acc8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8b9c50c-19c6-4a35-8b8a-29fb91861d42'), primary_key=True, serialize=False, unique=True),
        ),
    ]
