# Generated by Django 3.2.5 on 2021-12-26 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20211226_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8a2c6070-4078-4669-aa00-bac9bb832193'), primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SEEN', 'SEEN'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='UPCOMING', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='business.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('018964c7-1502-451e-ad12-250cfd2f1356'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bcb5271-850d-457c-8d60-52b465af76dd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61d84164-2419-4403-b118-0fcfb05a5728'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b90da404-1342-497e-b05a-391e3e9b5d97'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e1c32a5-6045-4e7e-a9bc-c124fe516230'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa4c4ffb-a0a8-45dd-b10e-cea696637d4c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c612ec0-a82a-4fb3-8ece-a654d7138b2c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business.request')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictEmployeeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7abb7486-9f59-43e8-a354-b3e0ee68e0fe'), primary_key=True, serialize=False, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='business.districtemplyoee')),
            ],
        ),
    ]
