# Generated by Django 3.2.5 on 2021-12-26 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('business', '0016_auto_20211226_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtemployeeline',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='inventory.line'),
        ),
    ]
