# Generated by Django 3.2.5 on 2021-12-26 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_districtemployeeline_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6d45607-0476-45ea-913d-60d73ceecdc4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afe87c9d-ef23-4935-880d-aef93888d642'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a9ba000-865f-4be0-9f7f-911e50c9f879'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemployeeline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8729e209-b3b2-42f1-8d20-53a1f096486b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54925ba5-6ba8-4a94-bad6-04e2b4e4bbb4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e52dff1f-b854-4d25-b76d-3310d0ea92ca'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0551b3b-f1a0-45d4-97cf-8f328772a770'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca3e3b5d-0924-4aa7-8ccf-041272e63879'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88df3f72-3c48-492d-b90a-5e45fccb0ca0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
