# Generated by Django 3.2.5 on 2021-12-27 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20211226_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9149fb1b-3e53-42e0-b7b0-3d02f7ec0b4f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2de3538f-119a-43e7-aa3e-d95d4f98fbbb'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b48ca4b3-f6ec-4125-b694-efecce18f5db'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemployeeline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2de30fbd-e33e-4c56-b7c2-a4b407ba3835'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('987548f1-423a-44a7-8a21-9bccec489324'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2133a91f-6fd7-4e3f-8a2f-a69e717357ec'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ae7511a-94ce-4ef8-9830-352fc016bf6f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e5b390b-58bc-4f63-9912-249ca55ebf0f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19622215-87d8-4cb3-9e7f-c31e1781bd1b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
