# Generated by Django 3.2.5 on 2021-12-27 22:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20211227_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='id',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='request_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3e92d95-6b54-4a47-8212-b4480a806831'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ac6d2d2-ae4b-40f0-a455-aa85f75d8bd7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46b8b82e-0546-47cb-94f3-8eb9b2a9557b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemployeeline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4100a55-9fba-4d0f-a35c-75bde9ea2d4f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d35a86e-b5f0-474e-8b64-43ef033a1203'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b7dc406-4496-4c30-b2d1-5e37370fb5d3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4269bcbd-189e-4533-a077-c844431dc235'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d11f8729-ca02-47d9-b5ea-065d3b7ed5d9'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('56aad85a-5edf-4593-84d0-005f06a01c6c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
