# Generated by Django 3.2.5 on 2021-12-27 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20211227_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='type',
            field=models.CharField(choices=[('SICK', 'SICK'), ('CASUAL', 'CASUAL'), ('VACATION', 'VACATION'), ('NATIONAL_HOLIDAY', 'NATIONAL_HOLIDAY')], default='CASUAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.UUID('656dbfaf-ff66-44a3-99f5-3f601135708a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f9b0c42-5508-4128-a679-19e46a546d56'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdistrict',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80783af8-4f1d-4e5c-92e4-bc3d8e4a1097'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemployeeline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('523f96b8-232f-4df2-a3c4-fe5ab33cd7b8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='districtemplyoee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c9e8269-0275-4de8-aec9-4334eb9f1ca0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22ce4936-e8db-4cdb-9ceb-d1eb69474ff2'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13133729-ff31-4045-8b40-0baebcd6a884'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8fb95ae-fb7f-4a27-aca1-18281a971bdc'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dfebcf3b-acf9-407a-81f9-fb0fdfa2e9c8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
