# Generated by Django 3.2.5 on 2021-12-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_auto_20211227_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='request',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='business.request'),
            preserve_default=False,
        ),
    ]
