# Generated by Django 3.2.5 on 2021-12-29 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_alter_leaverequest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name', 'domain'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.CreateModel(
            name='DistrictBrick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricks', to='business.businessdistrict')),
            ],
        ),
    ]
