# Generated by Django 3.2.5 on 2022-01-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20211229_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leaves_balance',
            field=models.IntegerField(default=21),
        ),
    ]
