# Generated by Django 3.2.5 on 2021-12-26 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0012_auto_20211226_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fe79d52e-6b2d-4238-b92b-0ed34d77a4b0'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Plan title')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('has_parent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='business.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plan.plan')),
            ],
        ),
    ]
