# Generated by Django 3.2.5 on 2022-03-24 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_visitagenda_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitagenda',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
