# Generated by Django 3.2.5 on 2021-12-26 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20211226_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('255c69b0-2fcd-4092-89dd-82140cc3c229'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02b3d8df-84ba-400c-963f-a8295eede0d2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
