# Generated by Django 3.2.5 on 2022-03-25 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_visitagenda_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitagenda',
            name='date',
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ONGOING', 'ONGOING'), ('CLOSED', 'CLOSED')], default='NEW', max_length=255, verbose_name='Visit Approval Status'),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('IN-PROGRESS', 'IN-PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255, verbose_name='Visit History'),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date & Time of Visit'),
        ),
    ]
