# Generated by Django 3.2.5 on 2021-12-26 22:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20211226_2211'),
        ('plan', '0003_auto_20211226_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitagenda',
            name='rep',
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='business.businessclient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='plan.subplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ONGOING', 'ONGOING'), ('CLOSED', 'CLOSED')], default='NEW', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('857db070-75ef-4bbe-99f1-83a0026832db'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('460437d5-d8f7-45df-8d4e-2839c6615774'), primary_key=True, serialize=False, unique=True),
        ),
    ]
