# Generated by Django 3.2.5 on 2022-03-25 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20220325_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdetails',
            name='visit_agenda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='plan.visitagenda'),
            preserve_default=False,
        ),
    ]
