# Generated by Django 3.2.5 on 2021-12-26 22:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20211226_2232'),
        ('plan', '0004_auto_20211226_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3014c5b2-05d9-4855-875b-42f6ca6a2105'), primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('593d715a-67bd-4d03-b4f2-ac20c1d91949'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93292a1b-c2bc-4e41-a064-69c5965f0918'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4b707220-cde4-4d54-9bcd-61d7a06eb263'), primary_key=True, serialize=False, unique=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='plan.plan')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='business.request')),
            ],
        ),
    ]
