# Generated by Django 3.2.5 on 2022-03-25 12:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_visitdetails_visit_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255, verbose_name="Visit last entry's status")),
            ],
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='approval_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ONGOING', 'ONGOING'), ('CLOSED', 'CLOSED')], default='NEW', max_length=255, verbose_name='Visit Approval Status'),
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date & Time of Visit'),
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255, verbose_name='Visit History'),
        ),
        migrations.DeleteModel(
            name='VisitDetails',
        ),
    ]
