# Generated by Django 3.2.5 on 2021-12-26 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20211226_2322'),
        ('inventory', '0002_auto_20211226_2322'),
        ('plan', '0005_auto_20211226_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('12a8921b-b9ea-447a-afe9-72c38919aefb'), primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('DOUBLE', 'DOUBLE'), ('COACHED', 'COACHED')], default='SINGLE', max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='business.request')),
            ],
        ),
        migrations.CreateModel(
            name='VisitDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c87e6419-9ca3-4a4f-9475-fa3842063155'), primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3a3f7df3-0208-47c4-b36a-01750747e70a'), primary_key=True, serialize=False, unique=True)),
                ('feedback', models.CharField(default=0, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='inventory.product')),
            ],
        ),
        migrations.DeleteModel(
            name='VisitLog',
        ),
        migrations.AddField(
            model_name='visitagenda',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE'), ('COACHED', 'COACHED')], default='SINGLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64869b4d-4981-41c4-9767-487e3a3ab0c7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59acfb8c-871c-41cd-b4e9-902d4427f548'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b7fafac-afe7-4384-b2bd-6609f6d0cbe3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='visitproducts',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='plan.visitagenda'),
        ),
        migrations.AddField(
            model_name='doublevisit',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='plan.visitagenda'),
        ),
    ]
