# Generated by Django 3.2.5 on 2021-12-27 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211227_2013'),
        ('plan', '0006_auto_20211226_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4e25b61c-ba09-4811-9e9f-4086437b3f09'), primary_key=True, serialize=False, unique=True)),
                ('feedback', models.CharField(default=0, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='inventory.product')),
            ],
        ),
        migrations.AlterField(
            model_name='doublevisit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8affce3a-f856-42b2-9ab8-70813f256775'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf25b6d4-f043-4f4d-b10d-504552c0fcab'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c80c7c48-6c18-4b47-86b6-6854ca2684e5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc55dd24-5c75-4f57-994e-09db5b679a04'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b2ce5dc-9535-4772-9747-a12cb59a9350'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='VisitProducts',
        ),
        migrations.AddField(
            model_name='visitproduct',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='plan.visitagenda'),
        ),
    ]
