# Generated by Django 3.2.5 on 2021-12-27 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20211227_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublevisit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad04ae03-f45a-4b68-bcf0-661a13631d29'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aaf657e4-007f-4949-afcd-8fa219fe1bd0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2aeccb0-1010-4e24-9ef6-0b76bd28e519'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74a67193-0cae-426f-ad34-c13159621b06'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4abf6a5a-3de2-4166-b0d3-ddcedb0e0105'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitproduct',
            name='id',
            field=models.UUIDField(default=uuid.UUID('435baa84-34b9-49f1-a35b-47b468cb8c2a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
