# Generated by Django 3.2.5 on 2021-12-27 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20211227_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublevisit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6598fa07-666f-424b-8d92-17b27654f351'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e5d008b-abe4-4031-bb92-e15d439fb7e1'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('879babc0-2b8c-4de1-b865-1432afb85efc'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d61a5db-c113-4f39-ba30-52d14eb67705'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('33e74306-7d43-41ee-b585-b4d4b9d37d72'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitproduct',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9885252-fd62-41ec-9e33-228fac8657ee'), primary_key=True, serialize=False, unique=True),
        ),
    ]
