# Generated by Django 3.2.5 on 2022-03-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_visitlog_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='status',
        ),
    ]
