# Generated by Django 3.2.5 on 2021-12-27 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20211227_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublevisit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77884636-8ed3-4eb7-aa1e-fb8baa98ecf8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('474b3bb0-6598-44d9-b61c-e97c2085f668'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9da00e71-5e79-4778-8c74-91c81f127c2f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ec20573-34ab-4405-9062-b26f81fc1ab8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22a36c5e-1335-482e-b520-dc4195c1082a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitproduct',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c59503a-d3a8-49b2-bf12-b6673c58abe8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
