# Generated by Django 3.2.5 on 2022-03-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_visitlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
    ]
