# Generated by Django 3.2.5 on 2021-12-27 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20211227_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublevisit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('905edb1b-286d-47fd-810f-29daa1204ed7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e58eb2b-d023-4e3e-8307-673429105fdd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('416eea28-985e-4f3a-9352-952c60873c17'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c2f410a-e35b-48d6-b08b-8080de345c9b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d8f1af9-fa43-4e82-a5c2-ca012b1a1b37'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitproduct',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53b57872-df6b-44d1-b0e9-f86487a6f1c5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
