# Generated by Django 3.2.5 on 2022-03-28 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20220327_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
