# Generated by Django 3.2.5 on 2022-03-29 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_subplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
