# Generated by Django 3.2.5 on 2022-04-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_subplan_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitagenda',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitagenda',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPCOMING', 'UPCOMING'), ('IN-PROGRESS', 'IN-PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255, verbose_name='Visit History'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPCOMING', 'UPCOMING'), ('IN-PROGRESS', 'IN-PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255, verbose_name="Visit last entry's status"),
        ),
    ]
