# Generated by Django 3.2.5 on 2022-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_auto_20220409_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitagenda',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
