# Generated by Django 3.2.5 on 2022-04-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_alter_visitagenda_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='activity',
            field=models.CharField(default='updated', max_length=255, verbose_name='Track visit activity'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPCOMING', 'UPCOMING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED'), ('MISSED', 'MISSED')], default='UPCOMING', max_length=255, verbose_name='Visit last entry status'),
        ),
    ]
